USE [POS]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetTotalSalesOfTheDay] AS BEGIN
 SELECT SUM(OrderTotal) AS TotalSalesOfTheDay
   FROM orders 
 WHERE CONVERT(DATE, OrderDate) = CONVERT(DATE, GETDATE());
END
